Controllers/OrderController.cs
using TawassolProject.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using TawassolProject.Data;
using TawassolProject.UnitOfWork;
using Microsoft.EntityFrameworkCore;

namespace TawassolProject.Controllers
{
    [Authorize]
    public class OrderController : Controller
    {
        private readonly ApplicationDbContext _context;
        private readonly UserManager<ApplicationUser> _userManager;
        private readonly IUnitOfWork _unitOfWork;



        public OrderController(ApplicationDbContext context , UserManager<ApplicationUser> userManager , IUnitOfWork unitOfWork)
        {
            _context = context;
            _userManager = userManager;
            _unitOfWork = unitOfWork;
        }



        public void CreateOrder(Order order)
        {
            order.OrderPlaced = DateTime.Now;
            order.OrderTotal = _unitOfWork.ShoppingCartRepository.GetShoppingCartTotalSum();
            var user = _userManager.GetUserId(User);
            order.UserId = user;
           
            _context.Orders.Add(order);
            _context.SaveChanges();

            var cartItems = _unitOfWork.ShoppingCartRepository.GetShoppingCartAllItemsAsync().Result;

            foreach (var product in cartItems)
            {
                var orderDetail = new OrderDetail()
                {
                    Amount = product.Amount,
                    productId = product.product.Id,
                    OrderId = order.OrderId,
                    Price = product.product.Price
                };

                _context.OrderDetails.Add(orderDetail);
            }

            _context.SaveChanges();
        }


        [Route("/orders/orders")]
        public IActionResult Index()
        {
            var user = _userManager.GetUserId(User);
            var orders = _context.Orders.Where(o => o.UserId == user).Include(d=>d.OrderLines).ToList();
            var userOrder = orders.FirstOrDefault(o => o.UserId == user);
            var userOrderId = userOrder?.OrderId;
            var orderDetails = userOrderId != null? _context.OrderDetails.Where(o => o.OrderId == userOrderId).Include(p => p.product).ToList(): new List<OrderDetail>(); 
            var oooo = new ShoppingCartViewModel
            {
                OrderList = orders,
                OrderDetails = orderDetails
            };

            return View(oooo);
        }






        public IActionResult Checkout()
        {
            var getOrder = new Order();
            var orderSum = _unitOfWork.ShoppingCartRepository.GetShoppingCartTotalSum();
            getOrder.OrderTotal = orderSum;


            var order = new ShoppingCartViewModel
            {
                CartItems = _unitOfWork.ShoppingCartRepository.GetShoppingCartAllItemsAsync().Result,
                order = getOrder
            };

            return View(order);
        }

        [HttpPost]
        public async Task<IActionResult> Checkout(Order order)
        {

            var cartItems = await _unitOfWork.ShoppingCartRepository.GetShoppingCartAllItemsAsync();
            if (cartItems.Count == 0)
            {
                ModelState.AddModelError("", "Cart is empty add products ");
            }

            if (ModelState.IsValid)
            {
                CreateOrder(order);
                _unitOfWork.ShoppingCartRepository.ClearCart();
                _unitOfWork.SaveChanges();
                return RedirectToAction("CheckoutComplete");
            }

            return View(order);
        }




        public IActionResult CheckoutComplete()
        {
            ViewBag.CheckoutCompleteMessage = "Checkout is Complete , Thanks for your order";

            return View();
        }


    }





}


Controllers/ProductsController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using TawassolProject.Data;
using TawassolProject.IRepository;
using TawassolProject.Models;
using TawassolProject.UnitOfWork;
using TawassolProject.ViewModel;
using static TawassolProject.Contants.Permissions;

namespace TawassolProject.Controllers
{
    public class ProductsController : Controller
    {
        private readonly ApplicationDbContext _context;
        private readonly IWebHostEnvironment _hosting;
        private readonly IUnitOfWork _unitOfWork;
        public ProductsController(ApplicationDbContext context, IWebHostEnvironment hosting , IUnitOfWork unitOfWork)
        {
            _context = context;
            _hosting = hosting;
            _unitOfWork = unitOfWork;
        }

        [Route("/products/main")]
        //[Authorize(Roles = "Admin")]

        public async Task<IActionResult> Index()
        {
            var productslist = await  _unitOfWork.ProductsRepository.GetAllAsync();

            var productsListt = productslist.Select(p => new ProductsViewModel
            {
                // Map properties from Product to ProductsViewModel
                Id = p.Id,
                Name = p.Name,
                DepartmentName = p.Department != null ? p.Department.Name : "No Department",
                CategoryName = p.Category != null ? p.Category.Name : "No Category",
                ProductImage=p.ProductImage
                // Other necessary mappings
            }).ToList();
            return View(productsListt);
        }


        public async Task<IActionResult> Details(int? id )
        {
            if (id == null)
            {
                return NotFound();
            }

            var product = await _unitOfWork.ProductsRepository.GetByIdAsync(id);

            if(product == null)
            {
                return NotFound();
            }
            
            var viewmodel = new ProductsViewModel
            {
               Name= product.Name,
               Description= product.Description,
               DepartmentId= product.DepartmentId,
               CategoryId=product.CategoryId,
               Brand=product.Brand,
               Price=product.Price,
               ProductImage=product.ProductImage,
               ProductGallery = product.Gallery,
               ProductAlot=await _unitOfWork.ProductsRepository.GetAllAsync(),
             };

            return View(viewmodel);
        }

        [Authorize(Roles ="Admin")]
        [HttpGet]
        public async Task<IActionResult> Create()
        {

            ViewBag.DepartmentId = new SelectList(await _unitOfWork.DepartmentsRepository.GetAllAsync(), "Id", "Name");
            ViewBag.CategoryId = new SelectList(await _unitOfWork.CategoryRepository.GetAllAsync(), "Id", "Name");

            return View();
        }


        
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(ProductsViewModel pvm)
        {

            if (!ModelState.IsValid)
            {
                
                return View("Create");
            }

            await _unitOfWork.ProductsRepository.CreateAsync(pvm);
           
            
            return View();
        }





        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var product = await _unitOfWork.ProductsRepository.GetByIdAsync(id);

            if (product == null)
            {
                return NotFound();
            }


            var viewmodel = new ProductsViewModel
            {
               Id= product.Id,
               Name = product.Name,
               Description = product.Description,
               Brand = product.Brand,
               Price = product.Price,
               ProductImage = product.ProductImage,
               ProductGallery = product.Gallery,
               DepartmentId = product.DepartmentId,
               CategoryId = product.CategoryId,
               DepartmentName=product.Department.Name,
               CategoryName=product.Category.Name,
                
            };


            ViewBag.CategoryId = new SelectList(_unitOfWork.CategoryRepository.GetAllByDepartmentId(viewmodel.DepartmentId), "Id", "Name", viewmodel.CategoryId);
            ViewBag.DepartmentId = new SelectList(await _unitOfWork.DepartmentsRepository.GetAllAsync(), "Id", "Name", viewmodel.DepartmentId);
            return View(viewmodel);
        }



        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int? id,ProductsViewModel pvm)
        {
            if (id == null)
            {
                return NotFound();
            }

            if (!ModelState.IsValid)
            {
                
                return View("Edit");
            }

            var product = await _unitOfWork.ProductsRepository.GetByIdAsync(id);

            if(product == null)
            {
                return NotFound();
            }

            string oldSingleImage = product.ProductImage;

            product.Price = pvm.Price;
            product.Description = pvm.Description;
            product.Name = pvm.Name;
            product.Brand = pvm.Brand;
            product.CategoryId = pvm.CategoryId;
            product.DepartmentId = pvm.DepartmentId;
            if(pvm.SingleImageUpload != null)
            {
                product.ProductImage = await _unitOfWork.ProductsRepository.SingleImageUploadAsync(pvm.SingleImageUpload);
                var oldImageDelete = Path.Combine(_unitOfWork.ProductsRepository.uploadFolderPublic, oldSingleImage);
                System.IO.File.Delete(oldImageDelete);
            }
            if(pvm.MultiImageUpload != null)
            {
                await _unitOfWork.ProductsRepository.MultiImageUploadAsync(pvm.MultiImageUpload, product);
            }

              
                await _context.SaveChangesAsync();

                return RedirectToAction(nameof(Index));
            
        }

        [Authorize(Roles = "Admin")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }
            var product = await _unitOfWork.ProductsRepository.GetByIdAsync(id);

            if (product == null)
            {
                return NotFound();
            }
            _unitOfWork.ProductsRepository.Delete(product);

            return View("Index");
        }



 




        private bool ProductExists(int id)
        {
            return _context.Products.Any(e => e.Id == id);
        }



        public IActionResult GetCategory(int depid)
        {
            var cat = _context.Categories.Where(c => c.DepartmentId == depid).ToList();
            return Ok(cat);
        }




        public IActionResult ProductInStockStatus(int? id)
        {

            var ppp = _context.Products.Find(id);

            ppp.InStock = !ppp.InStock;

            _context.SaveChanges();

            return Ok();
        }




        public IActionResult DeleteProductImageAjax(int? id)
        {
            string uploadfolderr = Path.Combine(_hosting.WebRootPath, "Uploads");

            string oldfile = _context.Galleries.Find(id).ImageURL;
            string pathh = Path.Combine(uploadfolderr, oldfile);
            System.IO.File.Delete(pathh);


            var productimagee = _context.Galleries.Find(id);
            _context.Galleries.Remove(productimagee);
            _context.SaveChanges();

            return Ok();

        }



        [Route("/products/info")]

        public async Task<IActionResult> productdetailstest(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var product = await _unitOfWork.ProductsRepository.GetByIdAsync(id);

            if (product == null)
            {
                return NotFound();
            }

            var allProduct = await _unitOfWork.ProductsRepository.GetAllAsync();
            var getProductSameCategory = allProduct.Where(p=>p.CategoryId==product.CategoryId).ToList();

            var viewmodel = new ProductsViewModel
            {
                 Id=product.Id,
                 Name= product.Name,
                 Description= product.Description,
                 Brand= product.Brand,
                 DepartmentName=product.Department.Name,
                 CategoryName=product.Category.Name,
                 Price=product.Price,
                 Specification=product.Specification,
                 ProductGallery=product.Gallery,
                 ProductAlot= getProductSameCategory,
                 ProductImage=product.ProductImage
            };



            return View(viewmodel);
        }





    }
}

Controllers/ShoppingCartController.cs
using TawassolProject.Data;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using TawassolProject.Models;
using Microsoft.AspNetCore.Authorization;
using TawassolProject.UnitOfWork;

namespace TawassolProject.Controllers
{
    [AllowAnonymous]
    public class ShoppingCartController : Controller
    {
        private readonly IUnitOfWork _unitOfWork;

        public ShoppingCartController(IUnitOfWork unitOfWork)
        {
            _unitOfWork = unitOfWork;
        }


        public async Task<IActionResult> Index()
        {
            
            var cartItems = await _unitOfWork.ShoppingCartRepository.GetShoppingCartAllItemsAsync();

            var scvm = new ShoppingCartViewModel
            {
                CartItems = cartItems,
                ShoppingCartTotal = _unitOfWork.ShoppingCartRepository.GetShoppingCartTotalSum(),
            };

            return View(scvm);

        }

        public async Task<IActionResult> AddToShoppingCart(int id)
        {
            var product = await _unitOfWork.ProductsRepository.GetByIdAsync(id);

            if(product != null)
            {
               await _unitOfWork.ShoppingCartRepository.AddToCartAsync(product);
               _unitOfWork.SaveChanges();
            }

            return RedirectToAction("Index");
        }
           


        public async Task<IActionResult> RemoveFromShoppingCart(int id)
        {
            var product = await _unitOfWork.ProductsRepository.GetByIdAsync(id);

            if (product != null)
            {
                await _unitOfWork.ShoppingCartRepository.RemoveFromCartAsync(product);
                _unitOfWork.SaveChanges();
            }

            return RedirectToAction("Index");

        }

        public async Task<IActionResult> increaseproductamount(int id)
        {
            var product = await _unitOfWork.ProductsRepository.GetByIdAsync(id);

            if (product != null)
            {
                int currentAmount = await _unitOfWork.ShoppingCartRepository.AddToCartAsync(product);
                _unitOfWork.SaveChanges();
                var totalAmount = _unitOfWork.ShoppingCartRepository.GetShoppingCartTotalSum();
                var singleTotalAmount = _unitOfWork.ShoppingCartRepository.GetShoppingCartSingleTotalSum(product);
                return Json(new { currentAmount , totalAmount , singleTotalAmount });
            }

            return BadRequest();
        }


        public async Task<IActionResult> decreaseproductamount(int id)
        {
            var product = await _unitOfWork.ProductsRepository.GetByIdAsync(id);

            if (product != null)
            {
                int currentAmount = await _unitOfWork.ShoppingCartRepository.RemoveFromCartAsync(product);
                _unitOfWork.SaveChanges();
                var totalAmount = _unitOfWork.ShoppingCartRepository.GetShoppingCartTotalSum();
                var singleTotalAmount = _unitOfWork.ShoppingCartRepository.GetShoppingCartSingleTotalSum(product);
                return Json(new { currentAmount , totalAmount , singleTotalAmount });
            }
            return BadRequest();

        }

        
        public IActionResult ClearCart()
        {
            _unitOfWork.ShoppingCartRepository.ClearCart();
            _unitOfWork.SaveChanges();
            return Json("Cart is empty");
        }


    }
}

Views/ShoppingCart/Index.cshtml
@model ShoppingCartViewModel

@*
    <div class="row checkoutForm">
        <h2>Your shopping cart</h2>
        <h4>Here are the drinks in your shopping cart.</h4>
        <table class="table table-bordered table-striped">
            <thead>
                <tr>
                    <th>Selected amount</th>
                    <th>Drink</th>
                    <th class="text-right">Price</th>
                    <th class="text-right">Subtotal</th>
                    <th></th>
                </tr>
            </thead>
            <tbody>
                @foreach (var line in Model.ShoppingCart.ShoppingCartItems)
                {
                    <tr>
                        <td class="text-center">@line.Amount</td>
                        <td class="text-left">@line.product.Name</td>
                        <td class="text-right">@line.product.Price.ToString("c")</td>
                        <td class="text-right">
                            @((line.Amount * line.product.Price).ToString("c"))
                        </td>
                        <td class="text-center">
                            <a class="btn btn-primary" asp-controller="ShoppingCart" asp-action="RemoveFromShoppingCart" asp-route-id="@line.product.Id"> remove</a>
                            <a class="btn btn-primary" asp-action="AddToShoppingCart" asp-controller="ShoppingCart" asp-route-id="@line.product.Id">Add more</a>

                        </td>

                    </tr>
                }
            </tbody>
            <tfoot>
                <tr>
                    <td colspan="3" class="text-right">Total:</td>
                    <td class="text-right">
                        @Model.ShoppingCartTotal.ToString("c")

                    </td>
                </tr>
            </tfoot>
        </table>


        @if (Model.ShoppingCart.ShoppingCartItems.Count > 0)
        {
            <div class="text-right">
                <div class="btn-group ">
                    <a class="btn btn-success" asp-controller="Order" asp-action="Checkout">Check out</a>
                </div>
            </div>
        }
        else
        {
            <p>error sorry </p>

        }

    </div>*@

<!-- Cart Start -->
<div class="container-fluid">
    <div class="row px-xl-5">
        <div class="col-lg-8 table-responsive mb-5">
            <table class="table table-light table-borderless table-hover text-center mb-0">
                <thead class="thead-dark">
                    <tr>
                        <th>Products</th>
                        <th>Price</th>
                        <th>Quantity</th>
                        <th>Total</th>
                        <th>Remove</th>
                    </tr>
                </thead>
                <tbody class="align-middle">
                    @if(Model.CartItems.Count == 0)
                    {
                        <tr>
                            <td></td>
                            <td></td>
                            <td class="align-middle">
                                <h2> Cart is empty</h2>
                                <a asp-action="shop" asp-controller="Products" class="btn btn-primary mt-3">Visit Shop</a>
                            </td>
                            <td></td>
                            <td></td>
                        </tr>
                    }
                    else
                    {
                        @foreach (var item in Model.CartItems)
                        {
                            <tr id="row-@item.product.Id">
                                <td class="align-middle"><img src="~/Uploads/products/@item.product.ProductImage" alt="" style="width: 50px;"> @item.product.Name</td>
                                <td class="align-middle">@item.product.Price.ToString("c")</td>
                                <td class="align-middle">
                                    <div class="input-group quantity mx-auto" style="width: 100px;">
                                        <div class="input-group-btn">
                                            <!-- Use a data attribute to store the product ID -->
                                            <form class="remove-from-cart-form" data-product-id="@item.product.Id">
                                                <button type="button" class="btn btn-sm btn-primary btn-minus">
                                                    <i class="fa fa-minus"></i>
                                                </button>
                                            </form>
                                        </div>
                                        <p class="form-control form-control-sm bg-secondary border-0 text-center">@item.Amount</p>
                                        <div class="input-group-btn">
                                            <!-- Use a data attribute to store the product ID -->
                                            <form class="add-to-cart-form" data-product-id="@item.product.Id">
                                                <button type="button" class="btn btn-sm btn-primary btn-plus">
                                                    <i class="fa fa-plus"></i>
                                                </button>
                                            </form>
                                        </div>
                                    </div>
                                </td>
                                <td class="align-middle" id="singletotalprice-@item.product.Id">@((item.Amount * item.product.Price).ToString("c"))</td>
                                <form class="remove-form" data-product-id="@item.product.Id">
                                <td class="align-middle"><button class="btn btn-sm btn-danger" id="removebtn"><i class="fa fa-times"></i></button></td>
                                </form>
                            </tr>
                        }
                    }
                </tbody>
            </table>
        </div>
        <div class="col-lg-4">
            <form class="mb-30" action="">
                <div class="input-group">
                    <input type="text" class="form-control border-0 p-4" placeholder="Coupon Code">
                    <div class="input-group-append">
                        <button class="btn btn-primary">Apply Coupon</button>
                    </div>
                </div>
            </form>
            <h5 class="section-title position-relative text-uppercase mb-3"><span class="bg-secondary pr-3">Cart Summary</span></h5>
            <div class="bg-light p-30 mb-5">
                <div class="border-bottom pb-2">
                    <div class="d-flex justify-content-between mb-3">
                        <h6>Subtotal</h6>
                        <h6>$150</h6>
                    </div>
                    <div class="d-flex justify-content-between">
                        <h6 class="font-weight-medium">Shipping</h6>
                        <h6 class="font-weight-medium">$10</h6>
                    </div>
                </div>
                <div class="pt-2">
                    <div class="d-flex justify-content-between mt-2">
                        <h5>Total</h5>
                        <h5 id="totalprice">@Model.ShoppingCartTotal.ToString("c")</h5>
                    </div>
                    <a asp-action="Checkout" asp-controller="Order" class="btn btn-block btn-primary font-weight-bold my-3 py-3">Proceed To Checkout</a>
                </div>
            </div>
        </div>
    </div>
</div>
<!-- Cart End -->

@section scripts {

    <script>
        $(document).ready(function () {
            $('.btn-plus').click(function () {
                var form = $(this).closest('.add-to-cart-form'); // Find the parent form
                var productId = form.data('product-id'); // Get the product ID from the data attribute

                $.ajax({
                    type: 'POST',
                    url: '@Url.Action("increaseproductamount", "ShoppingCart")',
                    data: { id: productId },
                    success: function (data) {
                        // Update the quantity on the page
                        var rowId = 'row-' + productId;
                        var quantityElement = $('#' + rowId + ' .quantity p');
                        quantityElement.text(data.currentAmount);
                        $('#totalprice').text('$' + data.totalAmount);
                        $('#singletotalprice' + '-' + productId).text('$' + data.singleTotalAmount);

                        // If you want to update the total as well, update it here
                    },
                    error: function () {
                        // Handle error if needed
                    }
                });
            });
             $('.btn-minus').click(function () {
                var form = $(this).closest('.remove-from-cart-form'); // Find the parent form
                var productId = form.data('product-id'); // Get the product ID from the data attribute

                $.ajax({
                    type: 'POST',
                    url: '@Url.Action("decreaseproductamount", "ShoppingCart")',
                    data: { id: productId },
                    success: function (data) {
                        // Update the quantity on the page
                        var rowId = 'row-' + productId;
                        var quantityElement = $('#' + rowId + ' .quantity p');
                        if (data.currentAmount > 0)
                        {
                            quantityElement.text(data.currentAmount);
                        }
                        else
                        {
                            $('#' + rowId).remove(); // Remove the entire row from the table
                        }
                        $('#totalprice').text('$' + data.totalAmount);
                        $('#singletotalprice' + '-' + productId).text('$' + data.singleTotalAmount);


                        // If you want to update the total as well, update it here
                    },
                    error: function () {
                        // Handle error if needed
                    }
                });
            });
        });
    </script>
    <script>
        $(document).ready(function () {
            $('#removebtn').on('click', function () {
                var form = $(this).closest('.remove-form'); // Find the parent form
                var productId = form.data('product-id'); // Get the product ID from the data attr
                $.ajax({
                    url: '@Url.Action("ClearCart", "ShoppingCart")',
                    type: 'GET', 
                    success: function (response) {
                        var rowId = 'row-' + productId;
                        $('#' + rowId).remove();
                    },
                    error: function (xhr, status, error) {
                        console.error('Error:', error);
                    }
                });
            });
        });

    </script>
}

Views/ShoppingCart/_cartcontrol.cshtml
@model ShoppingCartViewModel


    @foreach (var line in Model.ShoppingCart.ShoppingCartItems)
    {
        
                  <p class="form-control form-control-sm bg-secondary border-0 text-center">@line.Amount</p>
                   
    }