Models/Category.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace TawassolProject.Models
{
    public class Category
    {

        public int Id { get; set; }

        public string Name { get; set; }

        public string CategoryImage { get; set; }



        //relation
        public int DepartmentId { get; set; }

        public Department Department { get; set; }

        public virtual ICollection<Product> Productss { get; set; }


    }
}

Controllers/CategoriesController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using TawassolProject.Data;
using TawassolProject.Models;
using TawassolProject.UnitOfWork;
using TawassolProject.ViewModel;

namespace TawassolProject.Controllers
{

    [AllowAnonymous]
    public class CategoriesController : Controller
    {
        private readonly IUnitOfWork _unitOfWork;


        public CategoriesController(IUnitOfWork unitOfWork)
        {
            _unitOfWork = unitOfWork;
        }

        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> Index()
        {
            var categorylist = await _unitOfWork.CategoryRepository.GetAllAsync();
            var cat = categorylist.Select(c => new CategoriesViewModel
            {
                Id = c.Id,
                Name = c.Name,
                DepartmentName=c.Department.Name
            });
            return View(cat);
        }

        [Authorize(Roles = "Admin")]

        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var category = await _unitOfWork.CategoryRepository.GetByIdAsync(id);

            if (category == null)
            {
                return NotFound();
            }

            var cat = new CategoriesViewModel
            {
                Id=category.Id,
                Name= category.Name,
                DepartmentName=category.Department.Name,
                Productss=category.Productss,
            };


            return View(cat);
        }


        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> Create()
        {
            ViewBag.DepartmentId = new SelectList(await _unitOfWork.DepartmentsRepository.GetAllAsync(), "Id", "Name");
            return View();
        }

       
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(CategoriesViewModel cvm)
        {
            if (!ModelState.IsValid)
            {
                return View("Create");
            }

            await _unitOfWork.CategoryRepository.CreateAsync(cvm);
            _unitOfWork.SaveChanges();

            return RedirectToAction(nameof(Index));

        }

        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var category = await _unitOfWork.CategoryRepository.GetByIdAsync(id);

            if (category == null)
            {
                return NotFound();
            }
            var cat = new CategoriesViewModel
            {
                Id = category.Id,
                Name = category.Name,
                DepartmentName = category.Department.Name,
                Productss = category.Productss,
            };


            ViewBag.DepartmentId = new SelectList(await _unitOfWork.DepartmentsRepository.GetAllAsync(), "Id", "Name", category.DepartmentId);
            return View(cat);
        }

        // POST: Categories/Edit/5           
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(CategoriesViewModel cvm)
        {


            if (ModelState.IsValid)
            {
                return View("Edit");
            }

            if(cvm.Id == null)
            {
                return NotFound();
            }

            var category = await _unitOfWork.CategoryRepository.GetByIdAsync(cvm.Id);
            if(category == null)
            {
                return BadRequest();
            }

            string oldCategoryImage = category.CategoryImage;

            category.Name = cvm.Name;
            category.DepartmentId=cvm.DepartmentId;
            if(cvm.SingleImageUpload != null)
            {
                category.CategoryImage = await _unitOfWork.CategoryRepository.SingleImageUploadAsync(cvm.SingleImageUpload);
                var oldImageDelete = Path.Combine(_unitOfWork.CategoryRepository.uploadFolderPublic, oldCategoryImage);
                System.IO.File.Delete(oldImageDelete);
            }
                
                                    
             return RedirectToAction(nameof(Index));
            
           
        }

        [Authorize(Roles = "Admin")]
        [HttpPost]
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var category = await _unitOfWork.CategoryRepository.GetByIdAsync(id);
            if (category == null)
            {
                return BadRequest();
            }
            _unitOfWork.CategoryRepository.Delete(category);
            _unitOfWork.SaveChanges();

            return View(category);
        }

        

        
    }
}

Controllers/ProductsController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using TawassolProject.Data;
using TawassolProject.IRepository;
using TawassolProject.Models;
using TawassolProject.UnitOfWork;
using TawassolProject.ViewModel;
using static TawassolProject.Contants.Permissions;

namespace TawassolProject.Controllers
{
    public class ProductsController : Controller
    {
        private readonly ApplicationDbContext _context;
        private readonly IWebHostEnvironment _hosting;
        private readonly IUnitOfWork _unitOfWork;
        public ProductsController(ApplicationDbContext context, IWebHostEnvironment hosting , IUnitOfWork unitOfWork)
        {
            _context = context;
            _hosting = hosting;
            _unitOfWork = unitOfWork;
        }

        [Route("/products/main")]
        //[Authorize(Roles = "Admin")]

        public async Task<IActionResult> Index()
        {
            var productslist = await  _unitOfWork.ProductsRepository.GetAllAsync();

            var productsListt = productslist.Select(p => new ProductsViewModel
            {
                // Map properties from Product to ProductsViewModel
                Id = p.Id,
                Name = p.Name,
                DepartmentName = p.Department != null ? p.Department.Name : "No Department",
                CategoryName = p.Category != null ? p.Category.Name : "No Category",
                ProductImage=p.ProductImage
                // Other necessary mappings
            }).ToList();
            return View(productsListt);
        }


        public async Task<IActionResult> Details(int? id )
        {
            if (id == null)
            {
                return NotFound();
            }

            var product = await _unitOfWork.ProductsRepository.GetByIdAsync(id);

            if(product == null)
            {
                return NotFound();
            }
            
            var viewmodel = new ProductsViewModel
            {
               Name= product.Name,
               Description= product.Description,
               DepartmentId= product.DepartmentId,
               CategoryId=product.CategoryId,
               Brand=product.Brand,
               Price=product.Price,
               ProductImage=product.ProductImage,
               ProductGallery = product.Gallery,
               ProductAlot=await _unitOfWork.ProductsRepository.GetAllAsync(),
             };

            return View(viewmodel);
        }

        [Authorize(Roles ="Admin")]
        [HttpGet]
        public async Task<IActionResult> Create()
        {

            ViewBag.DepartmentId = new SelectList(await _unitOfWork.DepartmentsRepository.GetAllAsync(), "Id", "Name");
            ViewBag.CategoryId = new SelectList(await _unitOfWork.CategoryRepository.GetAllAsync(), "Id", "Name");

            return View();
        }


        
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(ProductsViewModel pvm)
        {

            if (!ModelState.IsValid)
            {
                
                return View("Create");
            }

            await _unitOfWork.ProductsRepository.CreateAsync(pvm);
           
            
            return View();
        }





        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var product = await _unitOfWork.ProductsRepository.GetByIdAsync(id);

            if (product == null)
            {
                return NotFound();
            }


            var viewmodel = new ProductsViewModel
            {
               Id= product.Id,
               Name = product.Name,
               Description = product.Description,
               Brand = product.Brand,
               Price = product.Price,
               ProductImage = product.ProductImage,
               ProductGallery = product.Gallery,
               DepartmentId = product.DepartmentId,
               CategoryId = product.CategoryId,
               DepartmentName=product.Department.Name,
               CategoryName=product.Category.Name,
                
            };


            ViewBag.CategoryId = new SelectList(_unitOfWork.CategoryRepository.GetAllByDepartmentId(viewmodel.DepartmentId), "Id", "Name", viewmodel.CategoryId);
            ViewBag.DepartmentId = new SelectList(await _unitOfWork.DepartmentsRepository.GetAllAsync(), "Id", "Name", viewmodel.DepartmentId);
            return View(viewmodel);
        }



        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int? id,ProductsViewModel pvm)
        {
            if (id == null)
            {
                return NotFound();
            }

            if (!ModelState.IsValid)
            {
                
                return View("Edit");
            }

            var product = await _unitOfWork.ProductsRepository.GetByIdAsync(id);

            if(product == null)
            {
                return NotFound();
            }

            string oldSingleImage = product.ProductImage;

            product.Price = pvm.Price;
            product.Description = pvm.Description;
            product.Name = pvm.Name;
            product.Brand = pvm.Brand;
            product.CategoryId = pvm.CategoryId;
            product.DepartmentId = pvm.DepartmentId;
            if(pvm.SingleImageUpload != null)
            {
                product.ProductImage = await _unitOfWork.ProductsRepository.SingleImageUploadAsync(pvm.SingleImageUpload);
                var oldImageDelete = Path.Combine(_unitOfWork.ProductsRepository.uploadFolderPublic, oldSingleImage);
                System.IO.File.Delete(oldImageDelete);
            }
            if(pvm.MultiImageUpload != null)
            {
                await _unitOfWork.ProductsRepository.MultiImageUploadAsync(pvm.MultiImageUpload, product);
            }

              
                await _context.SaveChangesAsync();

                return RedirectToAction(nameof(Index));
            
        }

        [Authorize(Roles = "Admin")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }
            var product = await _unitOfWork.ProductsRepository.GetByIdAsync(id);

            if (product == null)
            {
                return NotFound();
            }
            _unitOfWork.ProductsRepository.Delete(product);

            return View("Index");
        }



 




        private bool ProductExists(int id)
        {
            return _context.Products.Any(e => e.Id == id);
        }



        public IActionResult GetCategory(int depid)
        {
            var cat = _context.Categories.Where(c => c.DepartmentId == depid).ToList();
            return Ok(cat);
        }




        public IActionResult ProductInStockStatus(int? id)
        {

            var ppp = _context.Products.Find(id);

            ppp.InStock = !ppp.InStock;

            _context.SaveChanges();

            return Ok();
        }




        public IActionResult DeleteProductImageAjax(int? id)
        {
            string uploadfolderr = Path.Combine(_hosting.WebRootPath, "Uploads");

            string oldfile = _context.Galleries.Find(id).ImageURL;
            string pathh = Path.Combine(uploadfolderr, oldfile);
            System.IO.File.Delete(pathh);


            var productimagee = _context.Galleries.Find(id);
            _context.Galleries.Remove(productimagee);
            _context.SaveChanges();

            return Ok();

        }



        [Route("/products/info")]

        public async Task<IActionResult> productdetailstest(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var product = await _unitOfWork.ProductsRepository.GetByIdAsync(id);

            if (product == null)
            {
                return NotFound();
            }

            var allProduct = await _unitOfWork.ProductsRepository.GetAllAsync();
            var getProductSameCategory = allProduct.Where(p=>p.CategoryId==product.CategoryId).ToList();

            var viewmodel = new ProductsViewModel
            {
                 Id=product.Id,
                 Name= product.Name,
                 Description= product.Description,
                 Brand= product.Brand,
                 DepartmentName=product.Department.Name,
                 CategoryName=product.Category.Name,
                 Price=product.Price,
                 Specification=product.Specification,
                 ProductGallery=product.Gallery,
                 ProductAlot= getProductSameCategory,
                 ProductImage=product.ProductImage
            };



            return View(viewmodel);
        }





    }
}

Views/Categories/Create.cshtml
@model CategoriesViewModel

@{
    ViewData["Title"] = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@*<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="CategoryImage" class="control-label"></label>
                <input asp-for="CategoryImage" class="form-control" />
                <span asp-validation-for="CategoryImage" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="DepartmentId" class="control-label"></label>
                <select asp-for="DepartmentId" class ="form-control" asp-items="ViewBag.DepartmentId"></select>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>*@





<div class="container-fluid">
    <div class="row px-xl-5">
        <div class="col-lg-8">
            <h5 class="section-title position-relative text-uppercase mb-3"><span class="bg-secondary pr-3">Add New Category</span></h5>
            <div class="bg-light p-30 mb-5">
                <form asp-action="Create" method="post" enctype="multipart/form-data" asp-controller="Categories">
                    <div class="row">
                        <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                        <div class="col-md-6 form-group">
                            <label asp-for="Name" class="control-label"></label>
                            <input asp-for="Name" class="form-control" />
                            <span asp-validation-for="Name" class="text-danger"></span>
                        </div>
                        <div class="col-md-6 form-group">
                            <label asp-for="DepartmentId" class="control-label">Department Name</label>
                            <select asp-for="DepartmentId" class="form-control" asp-items="ViewBag.DepartmentId"></select>
                        </div>                                                               
                        <div class=" col-md-6 form-group">
                            <input type="submit" value="Create" class="btn btn-primary" />
                        </div>
                    </div>
                </form>
            </div>
            <div>
                <a class="btn btn-primary" asp-action="Index">Back To Categories List</a>
            </div>
        </div>
    </div>
</div>



@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Views/Categories/Delete.cshtml
@model CategoriesViewModel

@{
    ViewData["Title"] = "Delete";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this Category ?</h3>

   
    <hr />
    <div class="container-fluid pt-5">

        <table class="table table-bordered table-hover bg-light" id="myTable">
            <thead class="thead-dark">
                <tr>
                    <th>
                        @Html.Label("Category Name")
                    </th>
                    <th>
                        @Html.Label("Belongs to Department")
                    </th>
                    <th>
                        @Html.Label("Number of Products belong to this Category")
                    </th>
                    <th>@Html.Label("Action Links")</th>
                </tr>
            </thead>
            <tbody>

                <tr>
                    <td>
                        @Html.DisplayFor(modelItem => modelItem.Name)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => modelItem.Department.Name)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => modelItem.Productss.Count)
                    </td>
                    <td>
                        <form asp-action="Delete">
                            <input type="hidden" asp-for="Id" />
                            <input type="submit" value=" Confirm Category Delete" class="btn btn-outline-danger" />
                        </form>

                    </td>
                </tr>

            </tbody>
        </table>

        <a class="btn btn-primary" asp-action="Index">Return to Categories List</a>
        <a class="btn btn-primary" asp-action="Details" asp-route-id=@Model.Id>Back to this Category Details</a>

    </div>

Views/Categories/Details.cshtml
@model CategoriesViewModel

@{
    ViewData["Title"] = "Details";
    Layout = "~/Views/Shared/_Layout.cshtml";
}


<div class="container-fluid pt-5">
    <h4>Category Details</h4>
    <table class="table table-bordered table-hover bg-light" id="myTable">
        <thead class="thead-dark">
            <tr>
                <th>
                    @Html.Label("Category Name")
                </th>
                <th>
                    @Html.Label("Department Name")
                </th>
                <th>
                    @Html.Label("Total Number of Products belong to this Category")
                </th>
                <th>@Html.Label("Action Links")</th>
            </tr>
        </thead>
        <tbody>

            <tr>
                <td>
                    @Html.DisplayFor(modelItem => modelItem.Name)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => modelItem.DepartmentName)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => modelItem.Productss.Count)
                </td>
                <td>
                    <a class="btn btn-outline-primary" asp-action="Edit" asp-route-id="@Model.Id">Edit Category</a>
                    
                    <a class="btn btn-outline-danger" asp-action="Delete" asp-route-id="@Model.Id">Delete Category</a>
                </td>
            </tr>

        </tbody>
    </table>


    <h4> Related categories and departments </h4>

    <table class="table table-bordered table-hover bg-light" id="myTable2">

        <thead class="thead-dark">
            <tr>
                <th>
                    @Html.Label("Product Image")

                </th>
                <th>
                    @Html.Label("Product Name")
                </th>
                <th>
                    @Html.Label("Category Name")
                </th>
                <th>
                    @Html.Label("Department Name")
                </th>
                <th>
                    @Html.Label("Action Links")
                </th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model.Productss)
            {
                <tr>
                    <td>
                        <img src="~/Uploads/@item.ProductImage" style="width:50px;" class="img-thumbnail" />


                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Name)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Category.Name)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Department.Name)
                    </td>
                    <td>
                        <a class="btn btn-outline-primary" asp-action="Edit" asp-controller="Products" asp-route-id="@item.Id">Edit Product</a>
                        <a class="btn btn-outline-primary" asp-action="Details" asp-controller="Products" asp-route-id="@item.Id"> Product Details</a>
                        <a class="btn btn-outline-danger" asp-action="Delete" asp-controller="Products" asp-route-id="@item.Id">Delete Product</a>
                    </td>
                </tr>
            }
        </tbody>

    </table>
    <div>

        <a class="btn btn-primary" asp-action="Index">Back To Categories List</a>
    </div>
</div>



Views/Categories/Edit.cshtml
@model CategoriesViewModel

@{
    ViewData["Title"] = "Edit";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@* <div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>         
            <div class="form-group">
                <label asp-for="DepartmentName" class="control-label"></label>
                <select asp-for="DepartmentId" class="form-control" asp-items="ViewBag.DepartmentId"></select>
                <span asp-validation-for="DepartmentId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div> *@

<div class="container-fluid">
    <div class="row px-xl-5">
        <div class="col-lg-8">
            <h5 class="section-title position-relative text-uppercase mb-3"><span class="bg-secondary pr-3">Edit Category</span></h5>
            <div class="bg-light p-30 mb-5">
                <form asp-action="Create" method="post" enctype="multipart/form-data" asp-controller="Categories">
                    <input type="hidden" asp-for="Id" />
                    <div class="row">
                        <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                        <div class="col-md-6 form-group">
                            <label asp-for="Name" class="control-label"></label>
                            <input asp-for="Name" class="form-control" />
                            <span asp-validation-for="Name" class="text-danger"></span>
                        </div>
                        <div class="col-md-6 form-group">
                            <label asp-for="DepartmentName" class="control-label">Department Name</label>
                            <select asp-for="DepartmentId" class="form-control" asp-items="ViewBag.DepartmentId"></select>
                        </div>
                        <div class=" col-md-6 form-group">
                            <input type="submit" value="Create" class="btn btn-primary" />
                        </div>
                    </div>
                </form>
            </div>
            <div>
                <a class="btn btn-primary" asp-action="Index">Back To Categories List</a>
            </div>
        </div>
    </div>
</div>


@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Views/Categories/Index.cshtml
@model IEnumerable<CategoriesViewModel>

@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<head>
    <link href="~/css/datatables.css" rel="stylesheet" />
</head>

<div class="container-fluid pt-5">


    <p>
        <a class="btn btn-primary" asp-action="Create">Create New</a>
    </p>
    <table class="table table-bordered table-hover bg-light" id="myTable">
        <thead class="thead-dark">
            <tr>
                <th>
                    @Html.Label("Category Name")
                </th>            
                <th>
                    @Html.Label("Department Name")
                </th>
                <th>@Html.Label("Action Links")</th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model)
            {
                <tr>
                    <td>
                        @Html.DisplayFor(modelItem => item.Name)
                    </td>                   
                    <td>
                        @Html.DisplayFor(modelItem => item.DepartmentName)
                    </td>
                    <td>
                        <a class="btn btn-outline-primary" asp-action="Edit" asp-route-id="@item.Id">Edit</a>
                        <a class="btn btn-outline-primary" asp-action="Details" asp-route-id="@item.Id">Details</a>
                        <a class="btn btn-outline-primary" asp-action="Delete" asp-route-id="@item.Id">Delete</a>
                    </td>
                </tr>
            }
        </tbody>
    </table>
</div>
@section scripts{


    <script src="~/js/datatables.min.js"></script>

    <script>
            $(document).ready(function () {
                $('#myTable').DataTable();


            });
    </script>


}